version: "3.9"

services:
    
    traefik:
        image: traefik:3.3
        command:
            - --providers.docker=true
            - --providers.docker.exposedByDefault=false
            - --entryPoints.http.address=:80
            - --entryPoints.https.address=:443
            - --certificatesresolvers.myresolver.acme.tlschallenge=true
            - --certificatesresolvers.myresolver.acme.email=youremail@example.com
            - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./letsencrypt:/letsencrypt
        networks:
            - traefik-public
    
    nginx:
        build:
            context: .
            dockerfile: site/docker/production/nginx/Dockerfile
        container_name: nginx
        restart: always
        depends_on:
            - php-fpm
        volumes:
            - .:/var/www/html
            - ./site/docker/common/nginx/conf.d:/etc/nginx/conf.d
        labels:
            - traefik.enable=true
            - traefik.http.routers.site.rule=Host(`app.2bstock.ru`)
            - traefik.http.routers.site.entryPoints=https
            - traefik.http.routers.site.tls.certresolver=myresolver
        networks:
            - traefik-public
            - default
    
    php-fpm:
        build:
            context: .
            dockerfile: site/docker/production/php-fpm/Dockerfile
        container_name: php-fpm
        restart: always
        environment:
            APP_ENV: ${APP_ENV}
            DATABASE_URL: postgres://app:${POSTGRES_PASSWORD}@postgres:5432/app
            REDIS_URL: ${REDIS_URL}
        volumes:
            - .:/var/www/html
        networks:
            - default
    
    cli:
        build:
            context: .
            dockerfile: site/docker/production/cli/Dockerfile
        container_name: cli
        restart: always
        environment:
            APP_ENV: ${APP_ENV}
            DATABASE_URL: postgres://app:${POSTGRES_PASSWORD}@postgres:5432/app
            REDIS_URL: ${REDIS_URL}
        volumes:
            - .:/var/www/html
        networks:
            - default
    
    cli-migration:
        build:
            context: .
            dockerfile: site/docker/production/cli/Dockerfile
        container_name: cli-migration
        environment:
            APP_ENV: ${APP_ENV}
            DATABASE_URL: postgres://app:${POSTGRES_PASSWORD}@postgres:5432/app
            REDIS_URL: ${REDIS_URL}
        command: sh -c 'wait-for-it postgres:5432 -t 60 && php bin/console doctrine:migrations:migrate --no-interaction'
        volumes:
            - .:/var/www/html
        networks:
            - default
    
    postgres:
        image: postgres:15-alpine
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - default
    
    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        networks:
            - default

volumes:
    postgres_data:

networks:
    traefik-public:
        name: traefik-public
        driver: bridge
    default:
